name: Build and Test Feature Branch

on:
  pull_request:
    branches: [ develop ]
    types: [ opened, reopened ]

jobs:
  build-feature:
    runs-on: ubuntu-latest

    steps:
      ############################################################################################
      # - Download code from feature branch, setup java 17 and check that source code is buildable
      ############################################################################################
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: |
          mvn clean test package
          echo "Build with Maven"
